### DISCUSSION TITLE
rgd.yml

### DISCUSSION THREAD

**Discussion by sinlov** [sinlov-rs/gg#1] [General]
```yml
### repo ###
# github 用户名，支持个人或组织
owner: sinlov-rs
# github 仓库名称
repo: gg

### 可选配置，如果 type 为 `discussions2` 类型，才需要以下配置
# type: `issues` | `discussions` | `discussions2`, default is `discussions`
type: discussions

### website 配置
website:
  # 1. 格式为 png 的 240x240 正方形图片
  # 2. 在线图片 URL 地址，不设置则使用默认 logo
  # logo: https://user-images.githubusercontent.com/16164244/162659556-64dd7da8-321f-4525-bbbf-975f02b4800f.png
  # 网站标题
  title: sinlov-rs
  # 网站描述
  description: A gatsby website for rust discussions

### PWA Manifest 配置
# https://www.gatsbyjs.com/plugins/gatsby-plugin-manifest
manifest:
  name: sinlov-rs
  short_name: sinlov-rs
  start_url: /
  background_color: '#fafafa'
  theme_color: '#232629'
  display: standalone
  # 1. 格式为 png 的 240x240 正方形图片
  # 2. 在线图片 URL 地址，不设置则使用默认 logo
  # icon: https://avatars.githubusercontent.com/u/16164244?v=4
  # icon: https://user-images.githubusercontent.com/16164244/162659556-64dd7da8-321f-4525-bbbf-975f02b4800f.png
```
